layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
     - pushed
     - stars
  limit: 9
  exclude:
    archived: false
    #forks: true
    projects:
    #insert projects not to be displayed
    #- Sentiment_Analysis
    #-

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: VanHoannn
  # hackerrank: your_username
  instagram: _hoannn__
  # keybase: your_username
  linkedin: VanHoan
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Super Cat Technology Limited
    web_url: https://panoptic.ai/
    image_url: https://scontent-hkt1-2.xx.fbcdn.net/v/t1.6435-9/131405388_1672805419565754_3289542795491677346_n.png?_nc_cat=105&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=q_dFtpf0YcAAX-0l9T1&tn=UBwHquFHCm84-Axs&_nc_ht=scontent-hkt1-2.xx&oh=00_AT-xq--hrNLXJQz4fcG6SSVJw-Tjg7HH440UkpUZcSAJpA&oe=628B5EDC

  
