layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
     - pushed
     - stars
  limit: 9
  exclude:
    archived: false
    #forks: true
    projects:
    #insert projects not to be displayed
    #- Sentiment_Analysis
    #-

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: VanHoannn
  # hackerrank: your_username
  instagram: _hoannn__
  # keybase: your_username
  linkedin: VanHoan
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: PanopticAI
    web_url: https://panoptic.ai/
    image_url: https://secureservercdn.net/45.40.146.28/87v.d7e.myftpupload.com/wp-content/uploads/2020/10/GradientBlack_Fav.png?time=1650061020

  
